### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by MashedTuna** [peterhanania/Pogy-Old#27]
TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/runner/Sharona/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/runner/Sharona/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /home/runner/Sharona/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /home/runner/Sharona/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/runner/Sharona/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/runner/Sharona/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by AhmadShkour71** [comment]
he say error token
and close this and come in support guild
